version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./vol:/app/vol
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
