name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: "latest"
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: SSH into VM and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa tim.baiguzhinov@34.18.69.100 "
            cd /home/tim_baiguzhinov/translation_challenge &&
            chmod +x deploy.sh &&
            ./deploy.sh"
        shell: bash
